# Generated by Django 5.2 on 2025-04-17 19:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoe",
            name="discount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Discount as a percentage (e.g., 10.00 for 10%)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(100.0),
                ],
            ),
        ),
    ]
