# Generated by Django 5.0 on 2025-04-22 17:37

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shoe_discount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='last_edit',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
