# Generated by Django 5.2 on 2025-04-25 16:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_shoe_discount"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="shoe",
            name="subscribers",
            field=models.ManyToManyField(
                blank=True, related_name="subscribed_shoes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
