# Generated by Django 5.0 on 2025-04-28 21:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shoe_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='last_edit',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
