# Generated by Django 5.0 on 2025-04-29 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_shoe_last_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='seller',
            field=models.CharField(default='SoleMate', max_length=50),
            preserve_default=False,
        ),
    ]
