# Generated by Django 5.0 on 2025-04-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_shoe_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('discount_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
