# Generated by Django 5.2 on 2025-04-29 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_add_size_to_cartitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="discount_code",
            field=models.CharField(
                blank=True,
                help_text="Code applied at checkout, e.g. SOLEMATE15",
                max_length=20,
                null=True,
            ),
        ),
    ]
